"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SequencerSpecificEvent = exports.SMPTEOffsetEvent = exports.CuePointEvent = exports.MarkerEvent = exports.LyricEvent = exports.InstrumentNameEvent = exports.TextEvent = exports.TrackNameEvent = exports.CopyrightEvent = exports.ChannelPrefixEvent = exports.PortPrefixEvent = exports.SetTempoEvent = exports.KeySignatureEvent = exports.TimeSignatureEvent = exports.SequenceNumberEvent = void 0;
var SequenceNumber_1 = require("./SequenceNumber");
Object.defineProperty(exports, "SequenceNumberEvent", { enumerable: true, get: function () { return SequenceNumber_1.SequenceNumberEvent; } });
var TimeSignature_1 = require("./TimeSignature");
Object.defineProperty(exports, "TimeSignatureEvent", { enumerable: true, get: function () { return TimeSignature_1.TimeSignatureEvent; } });
var KeySignature_1 = require("./KeySignature");
Object.defineProperty(exports, "KeySignatureEvent", { enumerable: true, get: function () { return KeySignature_1.KeySignatureEvent; } });
var SetTempo_1 = require("./SetTempo");
Object.defineProperty(exports, "SetTempoEvent", { enumerable: true, get: function () { return SetTempo_1.SetTempoEvent; } });
var PortPrefix_1 = require("./PortPrefix");
Object.defineProperty(exports, "PortPrefixEvent", { enumerable: true, get: function () { return PortPrefix_1.PortPrefixEvent; } });
var ChannelPrefix_1 = require("./ChannelPrefix");
Object.defineProperty(exports, "ChannelPrefixEvent", { enumerable: true, get: function () { return ChannelPrefix_1.ChannelPrefixEvent; } });
var Copyright_1 = require("./Copyright");
Object.defineProperty(exports, "CopyrightEvent", { enumerable: true, get: function () { return Copyright_1.CopyrightEvent; } });
var TrackName_1 = require("./TrackName");
Object.defineProperty(exports, "TrackNameEvent", { enumerable: true, get: function () { return TrackName_1.TrackNameEvent; } });
var Text_1 = require("./Text");
Object.defineProperty(exports, "TextEvent", { enumerable: true, get: function () { return Text_1.TextEvent; } });
var InstrumentName_1 = require("./InstrumentName");
Object.defineProperty(exports, "InstrumentNameEvent", { enumerable: true, get: function () { return InstrumentName_1.InstrumentNameEvent; } });
var Lyric_1 = require("./Lyric");
Object.defineProperty(exports, "LyricEvent", { enumerable: true, get: function () { return Lyric_1.LyricEvent; } });
var Marker_1 = require("./Marker");
Object.defineProperty(exports, "MarkerEvent", { enumerable: true, get: function () { return Marker_1.MarkerEvent; } });
var CuePoint_1 = require("./CuePoint");
Object.defineProperty(exports, "CuePointEvent", { enumerable: true, get: function () { return CuePoint_1.CuePointEvent; } });
var SMPTEOffset_1 = require("./SMPTEOffset");
Object.defineProperty(exports, "SMPTEOffsetEvent", { enumerable: true, get: function () { return SMPTEOffset_1.SMPTEOffsetEvent; } });
var SequencerSpecific_1 = require("./SequencerSpecific");
Object.defineProperty(exports, "SequencerSpecificEvent", { enumerable: true, get: function () { return SequencerSpecific_1.SequencerSpecificEvent; } });
